version: '3'
services:
  source_postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'database'
    ports:
      - 5432:5432
    volumes:
      - source-postgres-data:/var/lib/postgresql/data/

volumes:
  source-postgres-data:
    