name: Create release and upload artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish assets for linux
        run: |
          dotnet publish -c Release -r linux-x64 -p:PublishingDir=${{ github.workspace }}/dist
      - name: Zip assets
        run: |
          ./scripts/createZipFolders.sh ./dist ./out
      - name: Upload Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./out/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
