// <auto-generated />
using Lingos.Source.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Lingos.Source.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201220164905_CreateSourcePostgresDB")]
    partial class CreateSourcePostgresDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Lingos.Common.Key", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_keys");

                    b.ToTable("keys");
                });

            modelBuilder.Entity("Lingos.Common.Locale", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("boolean")
                        .HasColumnName("deprecated");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.HasKey("Name")
                        .HasName("pk_locales");

                    b.ToTable("locales");
                });

            modelBuilder.Entity("Lingos.Common.Scope", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("boolean")
                        .HasColumnName("deprecated");

                    b.HasKey("Name")
                        .HasName("pk_scopes");

                    b.ToTable("scopes");
                });

            modelBuilder.Entity("Lingos.Common.Translation", b =>
                {
                    b.Property<string>("KeyName")
                        .HasColumnType("text")
                        .HasColumnName("key_name");

                    b.Property<string>("ScopeName")
                        .HasColumnType("text")
                        .HasColumnName("scope_name");

                    b.Property<string>("LocaleName")
                        .HasColumnType("text")
                        .HasColumnName("locale_name");

                    b.Property<string>("Variant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("variant");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("KeyName", "ScopeName", "LocaleName", "Variant")
                        .HasName("pk_translations");

                    b.HasIndex("LocaleName")
                        .HasDatabaseName("ix_translations_locale_name");

                    b.HasIndex("ScopeName")
                        .HasDatabaseName("ix_translations_scope_name");

                    b.ToTable("translations");
                });

            modelBuilder.Entity("Lingos.Common.Translation", b =>
                {
                    b.HasOne("Lingos.Common.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyName")
                        .HasConstraintName("fk_translations_keys_key_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lingos.Common.Locale", "Locale")
                        .WithMany()
                        .HasForeignKey("LocaleName")
                        .HasConstraintName("fk_translations_locales_locale_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lingos.Common.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeName")
                        .HasConstraintName("fk_translations_scopes_scope_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Key");

                    b.Navigation("Locale");

                    b.Navigation("Scope");
                });
#pragma warning restore 612, 618
        }
    }
}
